security:
    oauth2:
        client:
            clientId: ${client.id}
            clientSecret: ${client.secret}
            accessTokenUri: https://www.googleapis.com/oauth2/v3/token
            userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
            scope: email
            preEstablishedRedirectUri: http://localhost:8081
        resource:
            userInfoUri: https://www.googleapis.com/userinfo/v2/me
            preferTokenInfo: false
            
            
logging:
  level:
    ROOT: info